#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

AUTHORIZED_KEYS="/home/dokku/.ssh/authorized_keys"

case "$1" in

  ls-apps-json)
    set +o pipefail

    cd "$DOKKU_ROOT"
    for app in `ls -d */ | grep -v 'ssl\/' | sed -e 's,/$,,'`; do
      cid=$(cat $app/CONTAINER | cut -b1-12)

      if [[ -z $cid ]]; then
          continue
      fi

      url=$(cat $app/URL)
      psinfo=$(docker ps -a \
          | grep "$cid" \
          | awk -F '  +' -v q='"' '{OFS=","}
                { print ",\"created\":"q$4q,"\"status\":"q$5q }')
      echo "{\"id\":\"$cid\",\"name\":\"$app\",\"url\":\"$url\"$psinfo}"
    done

    set -o pipefail
  ;;
  ls-keys)
    if [[ -z $2 ]]; then
      echo "Missing username"
      exit 1
    fi
    grep "NAME=$2" $AUTHORIZED_KEYS \
        | awk '{print $1 " " $8}' \
        | sed 's/command="FINGERPRINT=//'
  ;;

  help)
    cat && cat<<EOF
    ls-apps-json                                    List all apps with status
    ls-keys                                         List all fingerprints for user
EOF
  ;;

esac

