#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

AUTHORIZED_KEYS="/home/dokku/.ssh/authorized_keys"

case "$1" in

  ls-apps-json)
    set +o pipefail

    cd "$DOKKU_ROOT"
    for app in `ls -d */ | grep -v 'ssl\/' | sed -e 's,/$,,'`; do
      cid=$(cat $app/CONTAINER | cut -b1-12)

      if [[ -z $cid ]]; then
          continue
      fi

      lastcommitHash=$(cat $app/refs/heads/master)
      lastcommit=$(cd $app && git cat-file commit `cat refs/heads/master` \
          | python -c 'import json,sys; print json.dumps(sys.stdin.read())')
      url=$(cat $app/URL)
      psinfo=$(docker ps -a \
          | grep "$cid" \
          | awk -F '  +' -v q='"' '{OFS=","}
                { print ",\"created\":"q$4q,"\"status\":"q$5q }')
      echo "{\"id\":\"$cid\",\"name\":\"$app\",\"url\":\"$url\"$psinfo,\"lastCommit\":$lastcommit,\"lastCommitHash\":\"$lastcommitHash\"}"
    done

    set -o pipefail
  ;;
  ls-keys)
    if [[ -z $2 ]]; then
      echo "Missing username"
      exit 1
    fi
    grep "NAME=$2" $AUTHORIZED_KEYS \
        | awk '{print $1 " " $8}' \
        | sed 's/command="FINGERPRINT=//'
  ;;
  rm-key)
    if [[ -z $2 ]] || [[ -z $3 ]]; then
      echo "Missing username or fingerprint"
      exit 1
    fi
    sed -i "/FINGERPRINT=$3\sNAME=$2/d" $AUTHORIZED_KEYS
  ;;

  help)
    cat && cat<<EOF
    ls-apps-json                                    List all apps with status
    ls-keys                                         List all fingerprints for user
    rm-key                                          Delete key for user
EOF
  ;;

esac

