#!/bin/bash
#
# List apps, running and dead
#

# httputils creates the associative arrays POST_PARAMS and GET_PARAMS
if [[ "$SCRIPT_FILENAME" ]]; then
  . "$(dirname $SCRIPT_FILENAME)/httputils"
else
  . "$(dirname $(pwd)$SCRIPT_NAME)/httputils"
fi

echo_apps_array() {
  local oldifs=$IFS
  IFS=$(echo -en "\n\b")
  local apps=( $(dokku ls-apps-json) )
  echo_json_array apps[@]
  IFS=$oldifs
}

do_GET() {
  echo "Status: 200 OK"
  echo "Cache-control: max-age=5"
  echo ""
  echo_apps_array
}

# Common headers
echo "Content-Type: application/json"

case $REQUEST_METHOD in
  GET)
    do_GET
    ;;
  *)
    do_405
    ;;
esac
