#!/bin/bash
#
# Get and set ENV for app
#

if [[ "$SCRIPT_FILENAME" ]]; then
  . "$(dirname $SCRIPT_FILENAME)/httputils"
else
  . "$(dirname $(pwd)$SCRIPT_NAME)/httputils"
fi

do_GET() {
  local app vars oldifs
  app="${GET_PARAMS['app']}"

  if [[ -z "$app" ]]; then
    do_400 "Missing query parameter 'app'" && return
  fi

  oldifs=$IFS
  IFS=$'\r\n'
  vars=( $(dokku config "$app" | awk -F ': +' 'NR > 1 {print $1,$2}') )
  IFS=$oldifs

  echo "Status: 200 OK"
  echo "Cache-control: max-age=4"
  echo ""
  echo_json_object vars[@]
}

# Common headers
echo "Content-Type: application/json"

case $REQUEST_METHOD in
  GET)
    do_GET
    ;;
  *)
    do_405
    ;;
esac
