#!/bin/bash
#
# Get environment for app
#

if [[ "$SCRIPT_FILENAME" ]]; then
  . "$(dirname $SCRIPT_FILENAME)/httputils"
else
  . "$(dirname $(pwd)$SCRIPT_NAME)/httputils"
fi

do_GET() {
  app="${GET_PARAMS['app']}"

  echo "Status: 200 OK"
  echo "Cache-control: max-age=4"
  echo ""
  dokku ls-env-json "$app"
}

# Common headers
echo "Content-Type: application/json"

case $REQUEST_METHOD in
  GET)
    do_GET
    ;;
  *)
    do_405
    ;;
esac
