#!/bin/bash
#
# List and add keys
#

# httputils creates the associative arrays POST_PARAMS and GET_PARAMS
if [[ "$SCRIPT_FILENAME" ]]; then
  . "$(dirname $SCRIPT_FILENAME)/httputils"
else
  . "$(dirname $(pwd)$SCRIPT_NAME)/httputils"
fi


echo_all_apps_array() {
  local apps=( $(dokku ls) )
  echo_json_array apps[@]
}

do_GET() {
  local keys oldifs
  oldifs=$IFS
  IFS=$'\r\n'
  keys=( $(dokku ls-keys $REMOTE_USER) )
  IFS=$oldifs

  echo "Status: 200 OK"
  echo "Cache-control: max-age=5"
  echo ""
  echo_json_array keys[@] true
}

do_POST() {
  pubkey="${POST_PARAMS['pubkey']}"
  if [[ -z "$REMOTE_USER" ]]; then
    do_401 "Username missing" && return
  elif [[ -z "$pubkey" ]]; then
    do_400 "Missing parameter 'pubkey'" && return
  fi

  # FIXME: Using sudo makes me feel naughty..
  fingerprint=$(echo -n "$pubkey" | sudo sshcommand acl-add dokku $REMOTE_USER)

  echo "Status: 201 OK"
  echo ""
  echo "{ \"fingerprint\": \"$fingerprint\" }"
}

# Common headers
echo "Content-Type: application/json"

case $REQUEST_METHOD in
  GET)
    do_GET
    ;;
  POST)
    do_POST
    ;;
  *)
    do_405
    ;;
esac
