#!/bin/bash
#
# List and add keys
#

# httputils creates the associative arrays POST_PARAMS and GET_PARAMS
if [[ "$SCRIPT_FILENAME" ]]; then
  . "$(dirname $SCRIPT_FILENAME)/httputils"
else
  . "$(dirname $(pwd)$SCRIPT_NAME)/httputils"
fi

do_GET() {
  local keys oldifs
  oldifs=$IFS
  IFS=$'\r\n'
  keys=( $(dokku ls-keys $REMOTE_USER) )
  IFS=$oldifs

  echo "Status: 200 OK"
  echo "Cache-control: max-age=5"
  echo ""
  echo_json_array keys[@] true
}

do_POST() {
  pubkey="${POST_PARAMS['pubkey']}"
  if [[ -z "$REMOTE_USER" ]]; then
    do_401 "Username missing" && return
  elif [[ -z "$pubkey" ]]; then
    do_400 "Missing POST parameter 'pubkey'" && return
  fi

  # FIXME: Using sudo makes me feel naughty..
  fingerprint=$(echo -n "$pubkey" | sudo sshcommand acl-add dokku $REMOTE_USER)

  echo "Status: 201 OK"
  echo ""
  echo "{ \"fingerprint\": \"$fingerprint\" }"
}

do_DELETE() {
  fingerprint=$( urldecode ${GET_PARAMS['fingerprint']} )
  if [[ -z "$REMOTE_USER" ]]; then
    do_401 "Username missing" && return
  elif [[ -z "$fingerprint" ]]; then
    do_400 "Missing query parameter 'fingerprint'" && return
  fi
  error_msg=$(dokku rm-key $REMOTE_USER $fingerprint)
  if [[ "$?" -ne 0 ]]; then
    do_500 "Something went wrong when trying to delete key: $error_msg"
    return
  fi
  echo "Status: 204 No Content"
  echo ""
}

# Common headers
echo "Content-Type: application/json"

case $REQUEST_METHOD in
  GET)
    do_GET
    ;;
  POST)
    do_POST
    ;;
  DELETE)
    do_DELETE
    ;;
  *)
    do_405
    ;;
esac
